---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: Install prerequisites
  become: true
  apt:
    pkg:
      - openjdk-17-jre-headless

- name: Ensure install directory exists
  file:
    path: "{{ install_dir }}"
    state: directory

- name: Download the installer
  get_url:
    url: "https://maven.fabricmc.net/net/fabricmc/fabric-installer/{{installer_version}}/fabric-installer-{{installer_version}}.jar"
    dest: "{{ install_dir }}/installer.jar"
    mode: 0740
  any_errors_fatal: true

- name: Run the installer to install Minecraft server
  shell:
    cmd: java -jar {{ install_dir }}/installer.jar server -mcversion {{ minecraft_version }} -downloadMinecraft
    chdir: "{{ install_dir }}"

- name: Remove the installer
  file:
    path: "{{ install_dir }}/installer.jar"
    state: absent

- name: Accept the EULA
  copy:
    dest: "{{ install_dir }}/eula.txt"
    content: |
      eula=true

- name: Copy config files to install directory
  copy:
    src: "{{ item }}"
    dest: "{{ install_dir }}"
  with_fileglob: "files/configs/*"

- name: Allow server port INPUT
  iptables:
    chain: INPUT
    jump: ACCEPT
    protocol: tcp
    destination_ports:
      - "25565"

- name: Template the service file to systemd directory
  template:
    src: templates/minecraft-server.service.j2
    dest: /etc/systemd/system/minecraft-server.service
    owner: root
    mode: 0644

- name: Copy socket file to systemd directory
  copy:
    src: files/minecraft-server.socket
    dest: /etc/systemd/system/
    owner: root
    mode: 0644

- name: Created named pipe
  command:
    cmd: mkfifo /run/minecraft-server.stdin
    creates: /run/minecraft-server.stdin

- name: Copy minecraft admin function
  copy:
    src: "files/mc-admin"
    dest: /usr/local/bin
    owner: root
    mode: 711